### ISSUE TITLE
DirectX11 not injecting

### ISSUE THREAD

**Issue by Pxpe123** [hiitiger/gelectron#124]
Dx11 Demo.exe (x64)
https://github.com/guitarfreak/DirectX-11-Demo/releases/tag/v0.6.3

When i attempt to run a dx11 demo and run my overlay its just logging
--------------------
 try inject DirectX 11 Demo

and nothing after  No game Ui no console logs nothing

Dx9 demo.exe (from here) works still though

**Comment by hiitiger** [comment]
the demo uses window title to find the process to inejct
your app window didn't set a title
you can change it or find the window using windowId (handle)

**Comment by Pxpe123** [comment]
Hey, i may be blind but i cant find what im ment to change to alter the target exe
Do you happen to know where specifically to look?

Sorry
