### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by MahdiFakhr** [hiitiger/gelectron#15]
hi , i can't use this program or even compile the demo version 

`npm link ../electron-overlay
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\programming\electron\gelectron-master\gelectron-master\electron-overlay
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-overlay@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1`

please add document i really need this 
Best regards.

**Comment by MahdiFakhr** [comment]
i stuck in 
 npm link ../electron-overlay

**Comment by MahdiFakhr** [comment]
i installed the python now i am getting this

`gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\anony\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\programming\electron\gelectron-master\gelectron-master\electron-overlay
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-overlay@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-overlay@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by hiitiger** [comment]
@MahdiFakhr 
node-gyp needs python2.
looks like you are using python3.7

**Comment by MahdiFakhr** [comment]
thank you sir , 
when you goingto complete the doc section ?
I really need this for my app.

You've done a great job

**Comment by MahdiFakhr** [comment]
i managed to run the demo , but i dont know how i can run this with my own electron app and own 3d game like what you did with cs go
