### ISSUE TITLE
How add hotkey ?

### ISSUE THREAD

**Issue by MahdiFakhr** [hiitiger/gelectron#17]
hello ,
is this possible to add hotkey like discord, so we can open the overlay by pressing the hotkey only ?
![image](https://user-images.githubusercontent.com/36822136/58759457-8ad29080-853f-11e9-8c8c-f73820d299c4.png)

if yes, can you guys give me tips for that. thank you

**Comment by hiitiger** [comment]
yeah, we can add hotkeys to control the overlay show/hide (intercepting user input in game) state.
In the demo, you can use F11 to control it, but that's just for demo.

You can send any hotkeys like this
```overlay.toggle``` is the name for a specific hotkey config, this is the one for you.

 ```TypeScript
this.Overlay.setHotkeys([
      { name: "overlay.toggle", keyCode: 113, modifiers: { ctrl: true } },
      { name: "app.doit", keyCode: 114, modifiers: { ctrl: true } }
    ])
```

**Comment by masudhossain** [comment]
@hiitiger is it possible to turn on the overlay WITHOUT a hotkey?
