### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by Juxstin** [hiitiger/gelectron#2]
c:\users\xen0n\gelectron\electron-overlay\src\overlay.h(15): fatal error C1083: Cannot open include file: 'boost/interp
rocess/windows_shared_memory.hpp': No such file or directory (compiling source file ..\src\main.cc) [C:\Users\Xen0n\gel
ectron\electron-overlay\build\electron_overlay.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Xen0n\gelectron\electron-overlay
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-overlay@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-overlay@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Xen0n\AppData\Roaming\npm-cache\_logs\2018-10-22T02_43_36_696Z-debug.log

**Comment by hiitiger** [comment]
@Juxstin have you done boost bootstrap for electron-overlay?
Also boost is not necessary, I will remove it soon.

**Comment by Juxstin** [comment]
http://wintertime.pw/sewny9dwwjiu4m3ffyri.png

I built it all now this happens when opening dx11app.exe

**Comment by hiitiger** [comment]
Try start it from visual studio. Resource files are loaded from current directory, so if start it from explorer you may need to copy fps.png to the output directory.

**Comment by Juxstin** [comment]
Ah, Thanks http://wintertime.pw/59q6n3f4waa2ag2hb1jf.png is this normal? for your current github with no boost

**Comment by hiitiger** [comment]
@Juxstin ye, try pull the latest repo, I cleaned up some code.

**Comment by Juxstin** [comment]
http://wintertime.pw/y7e854mgwk4266cpucck.png
When i npm Start


http://wintertime.pw/8ory59oqzlibdrd4a9m1.gif
When i click the start button

**Comment by hiitiger** [comment]
It seems the electron you are using is 64bit , and the addon is built as 32bit.
change value  of "compile:electron" in  gelectron/client/package.json to "electron-rebuild -v 2.0.8".

**Comment by Juxstin** [comment]
Ok it worked on the app works on all the directX apps provided

but on RobloxPlayerBeta.exe (DirectX 10 or 11 i forget) & other apps that are directX
it dosen't inject :( do i need to inject a DLL?

**Comment by hiitiger** [comment]
To inject to game you need to do the inject in your program,  there is a helper process gelectron\game-overlay\n_ovhelper, checkout its main implementation.

**Comment by Juxstin** [comment]
i fixed it ty i was dumb xd
