### ISSUE TITLE
Will the overlay work in Fullscreen? 

### ISSUE THREAD

**Issue by masudhossain** [hiitiger/gelectron#21]
Noticed this on the docs `we can assocciate a new IME conext if game disabled it, but in fullscreen it will cause window to lose focus.` not really sure what this really means. 

Can someone clarify if this will work with games that are full screen or not?

**Comment by hiitiger** [comment]
It work in fullscreen game.

But I did not handle IME associated messages, so in some game, it might caused the system's original IME input dialog to show
