### ISSUE TITLE
How performant is this?

### ISSUE THREAD

**Issue by nightshadecf** [hiitiger/gelectron#23]
Hello, as the title said, I'm curious about how performant is this approach. I really like the idea of streaming the texture inside the game. How good is this for a heavy ui? Thanks

**Comment by hiitiger** [comment]
It will hurt a bit performance, but depends on how complex the UI is.
For games like Dota 2, a window with player statistics barely hurt the FPS. 
But if play a 60 fps video in your window, it might decrease game FPS by 10 percent or more.

**Comment by nightshadecf** [comment]
thank you!
