### ISSUE TITLE
Injecting while in fullscreen

### ISSUE THREAD

**Issue by dpwolfe** [hiitiger/gelectron#40]
Hi @hiitiger,

Thank you for maintaining this project! I was trying to test this out with a couple games and I couldn't get it to work for World of Goo. The game only lets me play it in fullscreen mode, so I am switching out of it back to the overlay app to click the inject button. I couldn't get it to appear in the app while doing this. Do you think it's related to being in fullscreen and in not finding the window? Are there special considerations to get things working for games in fullscreen?

Thank you,

David

**Comment by dpwolfe** [comment]
@hiitiger I've been able to answer these questions myself. Thank you again for sharing this project.

**Comment by pluschong** [comment]
I also encountered the same problem. How did you solve it

**Comment by pluschong** [comment]
> @hiitiger我已经能够自己回答这些问题。再次感谢您分享这个项目。

I also encountered the same problem. How did you solve it

**Comment by dpwolfe** [comment]
@pluschong Try this and let me know if it works. Comment out this line which will re-enable the use of hardware acceleration: https://github.com/hiitiger/goverlay/blob/de1074e707168d2b3e075fd30325fc81bbbbcffc/client/src/main/main.ts#L9

This is the last change I made on 7/30. I think I may have been running into an OOM issue related to my particular hardware setup and this resolved it.

**Comment by pluschong** [comment]
> @pluschong试试这个，让我知道它是否有效。注释掉这一行，它将重新启用硬件加速的使用：
> 
> https://github.com/hiitiger/goverlay/blob/de1074e707168d2b3e075fd30325fc81bbbbcffc/client/src/main/main.ts#L9
> 
> 这是我在 7/30 所做的最后一次更改。我想我可能遇到了与我的特定硬件设置相关的 OOM 问题，这解决了它。

Thank you for your reply, I will try to change and test
