### ISSUE TITLE
i can't open the demo

### ISSUE THREAD

**Issue by gxsandzxl** [hiitiger/gelectron#5]
hello, i clone your code and want to open the demo, but i see something error, it exists when 'npm run start'

  
![_20181203192017](https://user-images.githubusercontent.com/35101675/49370871-7e0be600-f730-11e8-91f2-425bbec63a72.png)

best wishes

**Comment by hiitiger** [comment]
@gxsandzxl 
It seems the electron you are using is 64bit , and the addon is built as 32bit .
You can change value of "compile:electron" in gelectron/client/package.json to "electron-rebuild -v 2.0.8", and run "npm run compile:electron" again.
