### ISSUE TITLE
fatal error C1083: Cannot open include file: 'optional'

### ISSUE THREAD

**Issue by AtifMahmud** [hiitiger/gelectron#6]
On my windows 10 machine, when I run `npm link ../electron-overlay' from `client/` I get this error: 
Any fixes to this?

![image](https://user-images.githubusercontent.com/14244062/49499315-804e6d00-f822-11e8-9885-1a8cce3696a1.png)

**Comment by hiitiger** [comment]
@AtifMahmud 
You need  Visual Studio 2017 to build native project.
