### ISSUE TITLE
dx11app doesn't re-render overlay, unless resize window

### ISSUE THREAD

**Issue by kutu** [hiitiger/gelectron#8]
Overlay works fine with dx9app, but doesn't with dx11app

Video that demonstrate the issue https://youtu.be/o_4kfkJ3GMo

I use:
- win7 x64 SP1
- node v10.14.1
- electron 2.0.8
- `npm install --global --production windows-build-tools` to compile

I compile all code with `--msvs_version=2017`, without this parameter it fails to compile
`npm run compile:electron --msvs_version=2017`

Compile logs https://gist.github.com/kutu/3068190697791625e79d36d7def9f4cd
- electron-overlay
- game-overlay, dx9app, dx11app, n_overlay and n_ovhelper
  `"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" gameoverlay.sln /p:Configuration="Debug" /p:Platform="x64"`

I'm not C dev, but if you tell me what to try to do, I hope we can narrow down the issue.

**Comment by hiitiger** [comment]
looks like some rendering issues, I'm looking into it.

**Comment by kutu** [comment]
Any suggestions, at what part of code I should look to find the issue?
Does it work on your side, maybe its only my side issue?

**Comment by matthewpanetta** [comment]
Hey guys, I think I might have found the problem (or at least part of it)

In the n_overlay project, d3d11graphics.cc, scroll to line 310. There we swap syncState frame buffers with syncState_ (note the underscore at end) frame buffers. But if you scroll to line 432, we are checking for syncState_ which will always be size 0 after the swap (idk why). To fix this all you have to do is remove the _ from line 432 and line 434 and rebuild. It worked for me! I also removed the underscore from the other syncState_'s in that function block.

I have no knowledge of DX11 at all, but in the d3d10graphics and d3d9 graphics files there is no underscore either so I decided to try it out. Maybe this isn't the right way to do it? Idk

**Comment by kutu** [comment]
good catch, its working, thanks

**Comment by hiitiger** [comment]
It's a typo, fixed it with the latest commit.
